### PR TITLE
Feature/favourites

### PR DESCRIPTION
**Pull request by hassanwasfy**

### CODE REVIEW

**Comment by hassanwasfy** [comment]
Screenshot_20240323_012535

**Comment by hassanwasfy** [comment]
Screenshot_20240323_123055

**Comment by hassanwasfy** [comment]
Screenshot_20240323_124503
Screenshot_20240323_124524
Screenshot_20240323_124538

**Comment by amnah44** [comment]
Well done but we need to fix some things

- The background color of popup is not correct please check it again.
- The Dialog should to be a composable in the same package and if it not used in another place so should to be in the same screen but out side the content as private component to be more tidy.
- When I open the popup in the design there is a shadow on the layout behind the popup but it not found.

**Comment by hassanwasfy** [comment]
done, please check again @amnah44

**Review by yassenRamadan1 — APPROVED** [review]

**Review by amnah44 — APPROVED** [review]

**Pull request merged**
